


FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
EXPOSE 3000
CMD ["npm", "start"]




Explanation

Uses minimal Node.js Alpine base.

Installs production dependencies.

Copies code and exposes port 3000.

Starts app using npm start.



Final Outcome

A Node.js backend or frontend app container, usually for APIs or dashboards.
