version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mynodeapp:latest
    ports:
      - "8080:3000"
    volumes:
      - appdata:/usr/src/app
    depends_on:
      - redis
    restart: always
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    command: ["app.js"]
    entrypoint: ["node"]
    networks:
      - appnetwork

  redis:
    image: redis:alpine
    restart: on-failure
    networks:
      - appnetwork

volumes:
  appdata:

networks:
  appnetwork:
    driver: bridge

